name: CI/CD Pipeline para PythonAnywhere (MODO DEBUG)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Fazer checkout do código
        uses: actions/checkout@v4

      - name: 2. Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 3. Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Rodar Testes (Django Check)
        run: |
          python manage.py check

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Rodar Git Pull, Instalação e Migração (Tudo no Console)
        run: |
          COMMAND_STRING="source /home/livraria/.virtualenvs/vivarte-env-310/bin/activate && cd /home/livraria/VivArte && git pull origin main && pip install -r requirements.txt && python manage.py migrate\n"
          
          # --- MUDANÇA DE DEBUG AQUI ---
          # 1. Tenta criar o console e salva a resposta (JSON ou ERRO)
          CONSOLE_JSON=$(curl -X POST "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/consoles/" \
          -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
          -d "executable=bash")
          
          # 2. IMPRIME A RESPOSTA NO LOG PARA NÓS LERMOS
          echo "--- RESPOSTA DA API DO CONSOLE ---"
          echo "$CONSOLE_JSON"
          echo "----------------------------------"
          # --- FIM DA MUDANÇA DE DEBUG ---

          # 3. Tenta ler o JSON (vai falhar, mas tudo bem)
          CONSOLE_ID=$(echo $CONSOLE_JSON | python -c "import sys, json; print(json.load(sys.stdin)['id'])")

          echo "Console ID: $CONSOLE_ID"
          
          sleep 10
          
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/consoles/$CONSOLE_ID/send_input/" \
          -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
          -d "input=$COMMAND_STRING"

          sleep 60

      - name: 2. Recarregar (Reload) a Aplicação Web
        run: |
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/livraria.pythonanywhere.com/reload/" \
          -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}"

